---
# tasks file for httpd
- name: Ensure apache is at the latest version
  ansible.builtin.yum:
    name: httpd
    state: present
- name: Start service httpd, if not started
  ansible.builtin.service:
     name: httpd
     state: started
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'
